# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gradcheck?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gradcheck
    password: 1234