# 서버 포트 설정
server:
  port: 8080

# 데이터베이스 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://grad-check.mysql.database.azure.com:3306/
    username: gradcheck
    password: M9@Lp$3Xv!Kw5#t


