# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${GRAD_CHECK_DB_URL}
    username: ${GRAD_CHECK_DB_USERNAME}
    password: ${GRAD_CHECK_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# jwt
jwt:
  secret: ${GRAD_CHECK_JWT_SECRET}